INSERT INTO Empresa (Nome) VALUES ('Banco do Brasil')
INSERT INTO Empresa (Nome) VALUES ('Petrobrás')
INSERT INTO Empresa (Nome) VALUES ('Embraer')
INSERT INTO Empresa (Nome) VALUES ('Caixa Economica Federal')
INSERT INTO Empresa (Nome) VALUES ('Vale do Rio Doce')
INSERT INTO Empresa (Nome) VALUES ('Itaipu')
INSERT INTO Empresa (Nome) VALUES ('Usina Angra')
INSERT INTO Empresa (Nome) VALUES ('SERPRO')
INSERT INTO Empresa (Nome) VALUES ('BR Distribuidora')
INSERT INTO Empresa (Nome) VALUES ('ANVISA')